#!/usr/bin/env python3
"""Sync CV from config.toml and write shared/identity.tex from [applicant]."""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path
from urllib.request import Request, urlopen

try:
    import tomllib
except ModuleNotFoundError:
    import tomli as tomllib  # type: ignore

ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = ROOT / "config.toml"
CV_DIR = ROOT / "cv"
IDENTITY = ROOT / "shared" / "identity.tex"


def load_config() -> dict:
    if not CONFIG_PATH.is_file():
        sys.exit(f"Missing {CONFIG_PATH}")
    with CONFIG_PATH.open("rb") as f:
        return tomllib.load(f)


def tex_escape(s: str) -> str:
    return (
        s.replace("\\", "\\textbackslash{}")
        .replace("&", "\\&")
        .replace("%", "\\%")
        .replace("#", "\\#")
        .replace("_", "\\_")
    )


def write_identity(applicant: dict) -> None:
    IDENTITY.parent.mkdir(parents=True, exist_ok=True)
    name = applicant.get("name") or ""
    email = applicant.get("email") or ""
    homepage = applicant.get("homepage") or ""
    affiliation = applicant.get("affiliation") or ""
    phone = applicant.get("phone") or ""
    lines = [
        "% Auto-generated by scripts/sync_cv.py from config.toml — do not edit.",
        f"\\newcommand{{\\docauthor}}{{{tex_escape(name)}}}",
        f"\\newcommand{{\\docemail}}{{{tex_escape(email)}}}",
        f"\\newcommand{{\\dochomepage}}{{{tex_escape(homepage)}}}",
        f"\\newcommand{{\\docaffiliation}}{{{tex_escape(affiliation)}}}",
        f"\\newcommand{{\\docphone}}{{{tex_escape(phone)}}}",
        "",
    ]
    IDENTITY.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {IDENTITY.relative_to(ROOT)}")


def expand(p: str) -> Path:
    return Path(os.path.expanduser(p)).resolve()


def clear_cv_dir(keep_readme: bool = True) -> None:
    CV_DIR.mkdir(parents=True, exist_ok=True)
    for child in CV_DIR.iterdir():
        if keep_readme and child.name == "README.md":
            continue
        if child.is_dir():
            shutil.rmtree(child)
        else:
            child.unlink()


def resolve_main_tex(directory: Path) -> Path:
    for name in ("cv.tex", "main.tex", "CV.tex"):
        candidate = directory / name
        if candidate.is_file():
            return candidate
    texs = sorted(directory.glob("*.tex"))
    if len(texs) == 1:
        return texs[0]
    if not texs:
        sys.exit(f"No .tex files in {directory}")
    sys.exit(
        "Several .tex files in CV source; set [cv] path to the main file or name it cv.tex.\n"
        + "\n".join(f"  - {t.name}" for t in texs)
    )


def sync_local(path_str: str) -> Path:
    src = expand(path_str)
    if not src.exists():
        sys.exit(f"[cv].path not found: {src}")
    clear_cv_dir()
    if src.is_file():
        dest = CV_DIR / "cv.tex"
        dest.write_bytes(src.read_bytes())
        # Copy sibling support files (images, inputs) from the same directory
        for sib in src.parent.iterdir():
            if sib == src or sib.name.startswith("."):
                continue
            if sib.suffix.lower() in {".tex", ".sty", ".cls", ".bib", ".png", ".pdf", ".jpg", ".jpeg"}:
                target = CV_DIR / sib.name
                if sib.is_file() and not target.exists():
                    shutil.copy2(sib, target)
        print(f"CV ← {src}")
        return dest
    # Directory: copy tree
    for item in src.iterdir():
        if item.name.startswith("."):
            continue
        target = CV_DIR / item.name
        if item.is_dir():
            shutil.copytree(item, target)
        else:
            shutil.copy2(item, target)
    main = resolve_main_tex(CV_DIR)
    if main.name != "cv.tex":
        (CV_DIR / "cv.tex").write_text(f"% Auto-wrapper\n\\input{{{main.name}}}\n", encoding="utf-8")
    print(f"CV ← directory {src} (entry {main.name})")
    return CV_DIR / "cv.tex"


def sync_github(repo: str, path: str, ref: str) -> Path:
    if not repo:
        sys.exit("Set [cv].path or [cv].github_repo in config.toml")
    repo = repo.removeprefix("https://github.com/").removeprefix("git@github.com:").removesuffix(".git")
    raw = f"https://raw.githubusercontent.com/{repo}/{ref}/{path.lstrip('/')}"
    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
    headers = {"User-Agent": "dotfiles-academic-job-sync"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    req = Request(raw, headers=headers)
    try:
        with urlopen(req, timeout=60) as resp:
            data = resp.read()
    except Exception as e:
        # Fallback: shallow clone via git (handles private SSH remotes)
        print(f"raw.githubusercontent failed ({e}); trying git clone…")
        return sync_github_git(repo, path, ref)
    clear_cv_dir()
    dest = CV_DIR / "cv.tex"
    dest.write_bytes(data)
    print(f"CV ← {raw}")
    return dest


def sync_github_git(repo: str, path: str, ref: str) -> Path:
    cache = ROOT / ".cache" / "cv-repo"
    cache.parent.mkdir(parents=True, exist_ok=True)
    url_ssh = f"git@github.com:{repo}.git"
    url_https = f"https://github.com/{repo}.git"
    if cache.is_dir():
        subprocess.run(["git", "-C", str(cache), "fetch", "--depth", "1", "origin", ref], check=False)
        subprocess.run(["git", "-C", str(cache), "checkout", "FETCH_HEAD"], check=False)
    else:
        cloned = False
        for url in (url_ssh, url_https):
            r = subprocess.run(
                ["git", "clone", "--depth", "1", "--branch", ref, url, str(cache)],
                capture_output=True,
                text=True,
            )
            if r.returncode == 0:
                cloned = True
                break
            print(r.stderr.strip())
        if not cloned:
            sys.exit(f"Could not clone {repo}. Check SSH keys or set GITHUB_TOKEN for HTTPS raw fetch.")
    src = cache / path
    if not src.is_file():
        sys.exit(f"No file {path} in {repo}@{ref}")
    clear_cv_dir()
    # Copy file + same-directory support assets
    for sib in src.parent.iterdir():
        if sib.name.startswith("."):
            continue
        if sib.is_file():
            shutil.copy2(sib, CV_DIR / sib.name)
    main_name = src.name
    if main_name != "cv.tex":
        (CV_DIR / "cv.tex").write_text(f"% Auto-wrapper\n\\input{{{main_name}}}\n", encoding="utf-8")
    print(f"CV ← git {repo}@{ref}:{path}")
    return CV_DIR / "cv.tex"


def main() -> None:
    cfg = load_config()
    write_identity(cfg.get("applicant") or {})
    cv = cfg.get("cv") or {}
    path = (cv.get("path") or "").strip()
    repo = (cv.get("github_repo") or "").strip()
    if path:
        sync_local(path)
    elif repo:
        sync_github(repo, (cv.get("github_path") or "cv.tex").strip(), (cv.get("github_ref") or "main").strip())
    else:
        print(
            "No CV source yet — set [cv].path or [cv].github_repo in config.toml, then `just sync`.",
            file=sys.stderr,
        )
        CV_DIR.mkdir(parents=True, exist_ok=True)
        placeholder = CV_DIR / "cv.tex"
        if not placeholder.is_file():
            placeholder.write_text(
                "% Placeholder — configure [cv] in config.toml and run `just sync`.\n"
                "\\documentclass{article}\\begin{document}"
                "Set \\texttt{[cv]} in \\texttt{config.toml}."
                "\\end{document}\n",
                encoding="utf-8",
            )


if __name__ == "__main__":
    main()
